/* ============================================================
   SYNAPSE — Bibliothèque de contenu (français)
   Cartes d'idées personnalisées pour Marien.
   Chaque carte = un insight condensé, façon Deepstash.
   ============================================================ */

const THEMES = {
  neuro:   { id:'neuro',   nom:'Neuroplasticité', emoji:'🧠', couleur:'#38BDF8', desc:"Reconstruire ton cerveau, créer de nouvelles connexions." },
  trading: { id:'trading', nom:'Trading & marché', emoji:'📈', couleur:'#D4AF37', desc:"Devenir un trader stable et redoutable." },
  mental:  { id:'mental',  nom:'Mental & discipline', emoji:'🎯', couleur:'#EF6B6B', desc:"Forger un mental d'acier, dompter tes émotions." },
  physique:{ id:'physique',nom:'Physique & énergie', emoji:'💪', couleur:'#4ADE80', desc:"Un corps fort pour un cerveau fort." },
  appren:  { id:'appren',  nom:'Apprentissage & mémoire', emoji:'📚', couleur:'#A78BFA', desc:"Apprendre vite, retenir pour toujours." },
  reflex:  { id:'reflex',  nom:'Réflexion & décision', emoji:'🔍', couleur:'#60A5FA', desc:"Penser clair, décider juste." },
};

const CARTES = [
  /* ---------------- NEUROPLASTICITÉ ---------------- */
  { id:'n1', theme:'neuro', titre:"Ton cerveau se recâble à chaque instant",
    corps:"La neuroplasticité, c'est la capacité de ton cerveau à créer et renforcer de nouvelles connexions toute la vie — même après une lésion. Chaque chose que tu apprends trace un nouveau chemin neuronal. Ton cerveau n'est pas figé : il se reconstruit. Ce que tu répètes, il le grave.",
    source:"Neurosciences — plasticité cérébrale", auteur:"Fondation pour la Recherche sur le Cerveau" },
  { id:'n2', theme:'neuro', titre:"« Les neurones qui s'activent ensemble se lient ensemble »",
    corps:"C'est la loi de Hebb, le principe fondateur de l'apprentissage. Quand deux neurones s'activent en même temps, la connexion entre eux se renforce. Traduction : plus tu répètes une action ou une idée, plus le circuit devient solide et automatique. La répétition n'est pas ennuyeuse — c'est de la construction.",
    source:"Loi de Hebb (1949)", auteur:"Donald Hebb" },
  { id:'n3', theme:'neuro', titre:"Après une lésion, le cerveau se réorganise",
    corps:"Quand une zone est touchée, les zones voisines peuvent reprendre une partie du travail. De nouvelles routes se créent pour contourner les circuits abîmés. La récupération dépend beaucoup de la stimulation : plus tu sollicites ton cerveau avec des tâches variées, plus tu l'aides à se réparer. L'inaction, elle, laisse les connexions s'éteindre.",
    source:"Récupération après lésion cérébrale", auteur:"Neurosciences cliniques" },
  { id:'n4', theme:'neuro', titre:"Utilise-le ou perds-le",
    corps:"Les connexions neuronales sollicitées se renforcent ; celles qu'on n'utilise plus s'affaiblissent et disparaissent (c'est l'élagage synaptique). Ton cerveau est un jardin : ce que tu arroses pousse, ce que tu ignores fane. Chaque jour de stimulation compte. Chaque jour d'apprentissage protège et développe ton réseau.",
    source:"Élagage synaptique", auteur:"Neurosciences du développement" },
  { id:'n5', theme:'neuro', titre:"La nouveauté fait pousser ton cerveau",
    corps:"Apprendre quelque chose de nouveau et de difficile déclenche la libération de facteurs de croissance qui aident les neurones à se connecter. Le confort n'entraîne aucune plasticité. La difficulté, si. Cherche un peu d'inconfort chaque jour : une idée nouvelle, un geste nouveau, un problème que tu n'avais jamais résolu.",
    source:"Plasticité et apprentissage actif", auteur:"Neurosciences cognitives" },
  { id:'n6', theme:'neuro', titre:"Le sommeil grave tes progrès",
    corps:"Pendant que tu dors, ton cerveau rejoue et consolide ce que tu as appris dans la journée. Les connexions utiles sont renforcées, les inutiles nettoyées. Sans sommeil de qualité, tes efforts d'apprentissage s'effacent. Dormir n'est pas une perte de temps : c'est la moitié du travail de mémorisation.",
    source:"Consolidation mnésique", auteur:"Recherche sur le sommeil" },
  { id:'n7', theme:'neuro', titre:"Bouger nourrit tes neurones",
    corps:"L'exercice physique augmente le BDNF, une protéine qui agit comme un engrais pour le cerveau : elle favorise la naissance de nouveaux neurones et de nouvelles connexions, surtout dans l'hippocampe (la mémoire). 30 minutes de marche ou de sport, et ton cerveau devient littéralement plus apte à apprendre.",
    source:"BDNF & exercice", auteur:"Neurosciences de l'activité physique" },
  { id:'n8', theme:'neuro', titre:"La visualisation active les mêmes circuits que l'action",
    corps:"Imaginer précisément un geste active presque les mêmes réseaux neuronaux que l'exécuter réellement. C'est pour ça que les athlètes et les rééducateurs utilisent la visualisation : elle entretient et reconstruit les circuits même quand le corps ne peut pas encore agir. Visualise ce que tu veux devenir — ton cerveau commence déjà à le câbler.",
    source:"Imagerie motrice", auteur:"Neurosciences du mouvement" },

  /* ---------------- TRADING ---------------- */
  { id:'t1', theme:'trading', titre:"Le meilleur perdant gagne",
    corps:"Les meilleurs traders ne devinent pas mieux le marché. Ils perdent mieux : petit, vite, sans ego. La différence entre celui qui explose son compte et celui qui dure, ce n'est pas la qualité des entrées — c'est la gestion des pertes. Accepte de perdre proprement, et tu survivras assez longtemps pour gagner.",
    source:"Best Loser Wins", auteur:"Tom Hougaard" },
  { id:'t2', theme:'trading', titre:"80 % des traders retail perdent",
    corps:"Les chiffres publics des brokers européens sont brutaux : la grande majorité des particuliers perdent de l'argent. Ce n'est pas un hasard, c'est structurel — manque de discipline, sur-trading, gestion du risque absente. Ta mission n'est pas de rejoindre le troupeau, mais de faire exactement l'inverse de ce que fait la masse qui perd.",
    source:"Rapports AMF / ESMA", auteur:"Régulateurs européens" },
  { id:'t3', theme:'trading', titre:"Le stop-loss n'est pas une option",
    corps:"Décaler un stop-loss est l'acte le plus autodestructeur du trader. Une petite perte planifiée devient une catastrophe non planifiée. Ton stop est un contrat que tu signes avant d'entrer, quand ton cerveau est encore calme. Le respecter n'est pas une faiblesse : c'est la preuve que tu es un professionnel et pas un joueur.",
    source:"Gestion du risque", auteur:"Devenir un trader stable" },
  { id:'t4', theme:'trading', titre:"Risque 1 %, dure 100 trades",
    corps:"Si tu risques 1 % par trade, il te faudrait une série de pertes quasi impossible pour te ruiner. Si tu risques 10 %, dix pertes d'affilée — banales sur une série — et c'est fini. La survie précède le profit. Protège ton capital comme un sniper protège ses dernières balles : chaque trade doit être petit face à ton compte total.",
    source:"Money management", auteur:"Devenir un trader stable" },
  { id:'t5', theme:'trading', titre:"À +1500, ton cortex préfrontal s'éteint",
    corps:"Quand un trade gagne gros, la dopamine inonde ton cerveau et le cortex préfrontal — le siège de la décision rationnelle — se met en retrait. Tu deviens passager de tes émotions. C'est là qu'on rend tout : par euphorie. La parade : décider AVANT d'entrer où tu sors, et exécuter comme un robot quand l'émotion monte.",
    source:"Neurofinance", auteur:"Devenir un trader stable" },
  { id:'t6', theme:'trading', titre:"Perdre fait deux fois plus mal que gagner",
    corps:"Kahneman l'a prouvé : l'aversion à la perte fait qu'une perte de 100 € nous blesse deux fois plus qu'un gain de 100 € nous réjouit. C'est pour ça qu'on coupe les gagnants trop tôt et qu'on laisse courir les perdants. Connaître ce biais, c'est déjà commencer à le neutraliser : agis contre ton instinct, pas avec lui.",
    source:"Système 1 / Système 2", auteur:"Daniel Kahneman" },
  { id:'t7', theme:'trading', titre:"Un plan écrit vaut mille bonnes intentions",
    corps:"« Je verrai en direct » est la phrase des perdants. Le marché en direct, c'est de l'émotion pure. Ton edge, c'est un plan écrit : point d'entrée, stop, objectif, taille de position — décidés à froid. Le trade ne fait qu'exécuter une décision déjà prise. Pas de plan = pas de trade.",
    source:"Processus de trading", auteur:"Devenir un trader stable" },
  { id:'t8', theme:'trading', titre:"Tiens un journal de trading",
    corps:"Ce qui n'est pas mesuré ne s'améliore pas. Note chaque trade : le setup, ton émotion, si tu as respecté ton plan. En relisant, tu verras tes vrais schémas — pas ceux que tu imagines. Le journal transforme l'expérience en compétence. Sans lui, tu répètes les mêmes erreurs en croyant progresser.",
    source:"Amélioration continue", auteur:"Devenir un trader stable" },

  /* ---------------- MENTAL ---------------- */
  { id:'m1', theme:'mental', titre:"La discipline pèse des grammes, le regret pèse des tonnes",
    corps:"Chaque acte de discipline coûte un petit effort sur le moment. Chaque renoncement coûte un lourd regret plus tard. Choisis ta douleur : la petite, maintenant, qui construit — ou la grande, plus tard, qui détruit. Les monstres dans leur domaine ont juste appris à préférer la première.",
    source:"Discipline vs regret", auteur:"Jim Rohn (adapté)" },
  { id:'m2', theme:'mental', titre:"Tu ne montes pas au niveau de tes objectifs, tu tombes au niveau de tes systèmes",
    corps:"La motivation est un feu de paille. Ce qui te porte, ce sont tes routines : ce que tu fais automatiquement, sans négocier avec toi-même. Ne vise pas à être motivé chaque jour — construis des systèmes qui te font avancer même les jours sans envie. Le système bat la volonté.",
    source:"Atomic Habits", auteur:"James Clear" },
  { id:'m3', theme:'mental', titre:"Deviens 1 % meilleur chaque jour",
    corps:"1 % par jour, ça paraît ridicule. Mais sur un an, ça te rend environ 37 fois meilleur. Les résultats spectaculaires ne viennent pas d'un exploit unique, mais de l'accumulation de petits progrès invisibles. Ne cherche pas la transformation d'un coup. Cherche le petit progrès d'aujourd'hui, répété.",
    source:"Effet cumulé", auteur:"James Clear" },
  { id:'m4', theme:'mental', titre:"Entre le stimulus et la réaction, il y a un espace",
    corps:"Un événement te frappe — une perte, une insulte, un échec. Ton pouvoir est dans la fraction de seconde avant ta réaction. Les faibles réagissent automatiquement. Les forts utilisent cet espace pour choisir leur réponse. S'entraîner à faire une pause avant d'agir, c'est s'entraîner à la liberté.",
    source:"Logothérapie", auteur:"Viktor Frankl" },
  { id:'m5', theme:'mental', titre:"Concentre-toi sur ce que tu contrôles",
    corps:"Les stoïciens divisaient le monde en deux : ce qui dépend de toi (tes actes, ton effort, ton attitude) et ce qui n'en dépend pas (le résultat, l'avis des autres, le marché). Toute ton énergie doit aller dans la première colonne. Lâcher le reste, ce n'est pas abandonner — c'est arrêter de gaspiller ta force.",
    source:"Stoïcisme", auteur:"Épictète" },
  { id:'m6', theme:'mental', titre:"La constance bat l'intensité",
    corps:"Un effort énorme un jour, puis rien pendant deux semaines, ne construit rien. Un effort modéré tous les jours construit un empire. Ton cerveau et ton corps répondent à la régularité, pas aux coups d'éclat. Sois la goutte d'eau qui perce la pierre, pas la vague qui frappe une fois et se retire.",
    source:"Régularité", auteur:"Principe d'entraînement" },
  { id:'m7', theme:'mental', titre:"Nomme l'émotion pour la désamorcer",
    corps:"Quand tu mets un mot précis sur ce que tu ressens — « je suis en colère », « j'ai peur de perdre » — l'activité de l'amygdale baisse et ton cerveau rationnel reprend la main. C'est prouvé par imagerie cérébrale. Ne refoule pas tes émotions, nomme-les. Ce qui est nommé peut être dompté.",
    source:"« Name it to tame it »", auteur:"Dan Siegel" },
  { id:'m8', theme:'mental', titre:"Change d'identité, pas juste d'objectif",
    corps:"« Je veux arrêter de sur-trader » est un objectif fragile. « Je suis quelqu'un de discipliné » est une identité qui décide pour toi. Les habitudes durables ne viennent pas de ce que tu veux obtenir, mais de qui tu décides d'être. Chaque action est un vote pour la personne que tu deviens. Demande-toi à chaque choix : « qu'est-ce que ferait le trader que je veux devenir ? »",
    source:"Identity-based habits", auteur:"James Clear" },
  { id:'m9', theme:'mental', titre:"Tu deviens ce que tu répètes",
    corps:"Tu n'es pas ton passé ni ton accident. Tu es la somme de ce que tu fais chaque jour. Reconstruire une identité, c'est empiler des preuves : chaque trade discipliné, chaque carte apprise, chaque séance de sport est une brique. Au début tu joues un rôle ; à force de répétition, le rôle devient toi. La nouvelle personne se fabrique geste après geste.",
    source:"Construction de l'identité", auteur:"Psychologie du comportement" },
  { id:'m10', theme:'mental', titre:"Affronte ton défaut principal en face",
    corps:"On progresse le plus vite en travaillant précisément là où ça fait mal : ton plus gros défaut. L'ignorer le laisse grandir ; le regarder en face le réduit. Identifie le point faible qui te coûte le plus (l'impatience ? l'ego ? la peur ?) et fais-en ton chantier n°1. Ta plus grande faiblesse d'aujourd'hui peut devenir ta plus grande force.",
    source:"Croissance ciblée", auteur:"Développement personnel" },

  /* ---------------- PHYSIQUE ---------------- */
  { id:'p1', theme:'physique', titre:"Un cerveau fort a besoin d'un corps entraîné",
    corps:"Ton cerveau consomme environ 20 % de ton énergie. Sa performance dépend directement de ton corps : circulation, oxygénation, sommeil, nutrition. Négliger le physique, c'est saboter le mental. Le sport n'est pas séparé de la réflexion — c'en est le carburant.",
    source:"Corps-cerveau", auteur:"Physiologie" },
  { id:'p2', theme:'physique', titre:"L'exercice est ton meilleur antidépresseur naturel",
    corps:"Bouger libère des endorphines, de la dopamine et régule le cortisol (l'hormone du stress). 20 à 30 minutes d'activité suffisent à changer ton humeur et ta clarté mentale pour des heures. Quand la tête tourne mal, la solution est souvent dans les jambes : marche, cours, soulève.",
    source:"Exercice & humeur", auteur:"Médecine du sport" },
  { id:'p3', theme:'physique', titre:"Le sommeil est ta performance n°1",
    corps:"Manquer de sommeil dégrade la mémoire, le jugement, le contrôle émotionnel et la prise de risque — exactement les qualités d'un bon trader et d'un cerveau en reconstruction. Dormir 7 à 9 h n'est pas paresseux, c'est stratégique. Le sommeil est le socle sur lequel tout le reste tient.",
    source:"Why We Sleep", auteur:"Matthew Walker" },
  { id:'p4', theme:'physique', titre:"L'hydratation, c'est de la lucidité",
    corps:"Même une légère déshydratation (1 à 2 %) réduit la concentration, la mémoire de travail et l'humeur. Ton cerveau est composé à environ 75 % d'eau. Avant de chercher un café ou une excuse à ta fatigue mentale, bois un grand verre d'eau. Simple, gratuit, immédiat.",
    source:"Hydratation & cognition", auteur:"Neurophysiologie" },
  { id:'p5', theme:'physique', titre:"La respiration lente calme ton système nerveux",
    corps:"Ralentir ta respiration — inspiration 4 s, expiration 6 s — active le nerf vague et bascule ton corps en mode « repos ». En 90 secondes, ton rythme cardiaque baisse et ton cerveau redevient clair. C'est ton bouton d'urgence anti-panique : avant un trade, un examen, une décision importante.",
    source:"Cohérence cardiaque", auteur:"Physiologie du stress" },
  { id:'p6', theme:'physique', titre:"La lumière du matin règle ton horloge",
    corps:"Voir la lumière du jour dans l'heure qui suit ton réveil cale ton horloge biologique : meilleure énergie le jour, meilleur sommeil la nuit. 10 minutes dehors le matin valent mieux que trois cafés. Ton cerveau a besoin de savoir qu'il fait jour pour donner le meilleur de lui-même.",
    source:"Rythme circadien", auteur:"Neurosciences du sommeil" },

  /* ---------------- APPRENTISSAGE ---------------- */
  { id:'a1', theme:'appren', titre:"La répétition espacée grave dans le marbre",
    corps:"Réviser une information juste avant de l'oublier la renforce bien plus que la relire dix fois d'affilée. En espaçant tes révisions dans le temps, tu obliges ton cerveau à reconstruire le souvenir — et il devient plus solide à chaque fois. C'est le principe même de cette app : elle te fait revoir au bon moment.",
    source:"Courbe de l'oubli", auteur:"Hermann Ebbinghaus" },
  { id:'a2', theme:'appren', titre:"Se tester bat relire",
    corps:"Relire ses notes donne l'illusion de savoir. Se tester (récupérer l'info de mémoire, sans regarder) crée l'apprentissage réel. L'effort de rappel renforce la trace neuronale. Ferme le livre et demande-toi : « qu'est-ce que je viens d'apprendre ? » Cette petite gêne, c'est le son de ton cerveau qui grave.",
    source:"Testing effect", auteur:"Sciences cognitives" },
  { id:'a3', theme:'appren', titre:"Explique-le simplement, ou tu ne l'as pas compris",
    corps:"La technique Feynman : pour vérifier que tu maîtrises une idée, explique-la comme à un enfant, sans jargon. Là où tu bloques, c'est là que ta compréhension est trouée. Enseigner — même à un mur — est l'une des façons les plus puissantes d'apprendre et de consolider.",
    source:"Technique Feynman", auteur:"Richard Feynman" },
  { id:'a4', theme:'appren', titre:"Mélange tes sujets pour mieux apprendre",
    corps:"Travailler un seul type de problème en bloc semble efficace mais s'oublie vite. Alterner plusieurs sujets ou compétences (l'entrelacement) est plus dur sur le moment mais grave bien plus profond. La difficulté que tu ressens n'est pas un échec : c'est le signe que l'apprentissage se fait.",
    source:"Interleaving", auteur:"Sciences de l'apprentissage" },
  { id:'a5', theme:'appren', titre:"Les difficultés désirables",
    corps:"Ce qui rend l'apprentissage plus dur sur le moment — se tester, espacer, mélanger — le rend plus durable. À l'inverse, ce qui semble facile et fluide s'évapore. Ne fuis pas l'effort mental : c'est exactement lui qui construit les connexions solides. Le confort d'apprentissage est un piège.",
    source:"Desirable difficulties", auteur:"Robert Bjork" },
  { id:'a6', theme:'appren', titre:"5 minutes par jour battent 5 heures le dimanche",
    corps:"Un petit contact quotidien avec un sujet crée une progression que les longues sessions rares ne donnent jamais. La régularité entretient les circuits, empêche l'oubli et transforme l'apprentissage en habitude. C'est toute la logique de cette app : un peu, mais tous les jours, sans exception.",
    source:"Micro-apprentissage", auteur:"Sciences cognitives" },

  /* ---------------- RÉFLEXION ---------------- */
  { id:'r1', theme:'reflex', titre:"Système 1 rapide, Système 2 lent",
    corps:"Ton cerveau a deux vitesses : le Système 1, intuitif et immédiat (utile mais plein de biais), et le Système 2, lent et rationnel (fiable mais paresseux). Les grosses décisions — argent, vie, trading — méritent le Système 2. Apprends à reconnaître quand ton intuition te mène, et à imposer une pause réfléchie.",
    source:"Thinking, Fast and Slow", auteur:"Daniel Kahneman" },
  { id:'r2', theme:'reflex', titre:"Inverse le problème",
    corps:"Au lieu de te demander « comment réussir ? », demande « qu'est-ce qui me ferait échouer à coup sûr ? » puis évite-le. Cette inversion, chère à Charlie Munger, révèle des pièges qu'on ne voit pas de face. Souvent, éviter la bêtise rapporte plus que chercher le génie.",
    source:"Inversion", auteur:"Charlie Munger" },
  { id:'r3', theme:'reflex', titre:"Méfie-toi du biais de confirmation",
    corps:"Ton cerveau cherche naturellement ce qui confirme ce qu'il croit déjà, et ignore le reste. En trading, ça te fait voir sur le graphique ce que tu veux voir. Le remède : cherche activement les preuves que tu as tort. La question puissante n'est pas « ai-je raison ? » mais « et si je me trompais ? »",
    source:"Biais de confirmation", auteur:"Psychologie cognitive" },
  { id:'r4', theme:'reflex', titre:"Pense en probabilités, pas en certitudes",
    corps:"Le débutant veut avoir raison. Le pro pense en pourcentages : « ce setup gagne 6 fois sur 10 ». Un bon trade peut perdre, un mauvais trade peut gagner — sur un coup. Ce qui compte, c'est la qualité de la décision sur des centaines de coups. Détache-toi du résultat unique, juge le processus.",
    source:"Thinking in Bets", auteur:"Annie Duke" },
  { id:'r5', theme:'reflex', titre:"Le coût irrécupérable est un piège",
    corps:"« J'ai déjà tellement investi, je ne peux pas arrêter maintenant. » Erreur. Ce qui est dépensé est dépensé — argent, temps, position perdante. La seule question valable : à partir de maintenant, quelle est la meilleure décision ? Ne laisse pas ton passé décider de ton avenir.",
    source:"Sunk cost fallacy", auteur:"Économie comportementale" },
  { id:'r6', theme:'reflex', titre:"Ralentis pour aller plus vite",
    corps:"Les décisions prises dans la précipitation coûtent des heures à réparer. Prendre 30 secondes pour respirer et clarifier ton intention avant d'agir améliore radicalement la qualité de tes choix. Dans un monde qui pousse à réagir vite, la capacité à faire une pause devient un super-pouvoir.",
    source:"Décision réfléchie", auteur:"Sagesse pratique" },

  /* ---------------- AJOUTS ---------------- */
  { id:'n9', theme:'neuro', titre:"La dopamine grave ce qui compte",
    corps:"La dopamine n'est pas que le plaisir : c'est le marqueur qui dit à ton cerveau « ça, c'est important, garde-le ». Quand tu ressens une petite victoire — comprendre une idée, réussir un trade propre — ce pic de dopamine renforce le circuit. Célèbre tes micro-réussites : tu programmes ton cerveau à vouloir recommencer.",
    source:"Système de récompense", auteur:"Neurosciences" },
  { id:'n10', theme:'neuro', titre:"Sans attention, pas de plasticité",
    corps:"Ton cerveau ne se recâble que sur ce à quoi tu prêtes vraiment attention. Faire dix choses à la fois n'entraîne rien. Une concentration pleine sur une seule tâche ouvre la porte du changement neuronal. La concentration n'est pas un détail : c'est la condition même de l'apprentissage. Coupe les distractions, et ton cerveau se transforme.",
    source:"Focus & neuroplasticité", auteur:"Andrew Huberman" },
  { id:'n11', theme:'neuro', titre:"L'erreur ouvre la porte du cerveau",
    corps:"Se tromper libère des signaux (dopamine, acétylcholine) qui indiquent au cerveau : « quelque chose ne colle pas, adapte-toi ». C'est juste après une erreur que la plasticité est maximale — si tu restes et corriges. Ne fuis pas tes erreurs : c'est exactement le moment où ton cerveau est le plus prêt à apprendre.",
    source:"Apprentissage par l'erreur", auteur:"Neurosciences" },
  { id:'n12', theme:'neuro', titre:"La méditation muscle ton attention",
    corps:"Quelques minutes par jour à ramener ton attention sur ta respiration renforcent le cortex préfrontal (décision, contrôle de soi) et calment l'amygdale (peur, impulsivité). C'est un entraînement direct des zones qui te servent en trading et dans la vie. Méditer, c'est de la musculation pour ton self-control.",
    source:"Méditation & cerveau", auteur:"Neurosciences contemplatives" },

  { id:'t9', theme:'trading', titre:"Coupe court aux pertes, laisse courir les gains",
    corps:"La règle qui sépare les gagnants des perdants tient en une phrase. La plupart font l'inverse : ils encaissent vite un petit gain (peur de le perdre) et laissent grossir une perte (espoir qu'elle revienne). Fais le contraire de ton instinct : petite perte assumée, gain qu'on laisse respirer. C'est contre-nature, et c'est tout le métier.",
    source:"Règle d'or", auteur:"Devenir un trader stable" },
  { id:'t10', theme:'trading', titre:"Le marché ne te doit rien",
    corps:"Le marché n'a pas de mémoire de ton dernier trade, ne sait pas que tu as besoin d'argent, ne te récompensera pas pour ton effort. Il est neutre. Attendre une « revanche » ou une « justice » du marché, c'est le début de la ruine. Ton seul avantage : un processus à espérance positive, répété avec discipline.",
    source:"Réalité du marché", auteur:"Devenir un trader stable" },
  { id:'t11', theme:'trading', titre:"Ne rien faire est une position",
    corps:"L'envie de « trader pour trader » a ruiné plus de comptes que les mauvaises analyses. Attendre le bon setup, mains sur les genoux, est une compétence rare et rentable. Le marché est ouvert des milliers d'heures ; ton edge n'apparaît que quelques-unes. La patience n'est pas de l'inaction : c'est de la précision.",
    source:"Sur-trading", auteur:"Devenir un trader stable" },
  { id:'t12', theme:'trading', titre:"Juge le processus, pas le résultat",
    corps:"Un trade peut être parfaitement exécuté et perdre ; mal exécuté et gagner. Sur un coup, le hasard décide. Sur mille coups, c'est ton processus qui décide. Arrête de noter tes trades sur « gagné / perdu » et note-les sur « ai-je respecté mon plan ? ». Répète le bon process, et les résultats suivent.",
    source:"Variance & discipline", auteur:"Annie Duke (adapté)" },

  { id:'m11', theme:'mental', titre:"La règle des 2 minutes",
    corps:"Pour vaincre la procrastination, réduis l'action à sa version de 2 minutes : « ouvrir mon graphique », « mettre mes baskets », « lire une carte ». Une fois lancé, le plus dur est fait — le mouvement appelle le mouvement. Ne vise pas la séance parfaite : vise juste à commencer. Le démarrage est 90 % de la bataille.",
    source:"Atomic Habits", auteur:"James Clear" },
  { id:'m12', theme:'mental', titre:"La discipline, c'est la liberté",
    corps:"Ça semble paradoxal : se donner des règles strictes rend libre. La discipline te libère de tes impulsions, de tes humeurs, du chaos. Celui qui n'obéit à aucune règle est esclave de chaque envie. Choisis tes disciplines, et tu choisis ta liberté. Le relâchement, lui, finit toujours en prison de regrets.",
    source:"Discipline Equals Freedom", auteur:"Jocko Willink" },
  { id:'m13', theme:'mental', titre:"Compare-toi à toi d'hier",
    corps:"Te comparer aux autres, c'est courir une course truquée : tu ne vois que leurs sommets, jamais leurs galères. Le seul adversaire utile, c'est toi d'hier. Un peu mieux qu'hier, chaque jour : c'est mesurable, c'est motivant, et ça t'appartient. La vraie compétition est intérieure.",
    source:"Progrès personnel", auteur:"Jordan Peterson (adapté)" },

  { id:'p7', theme:'physique', titre:"Tiens-toi droit, ton cerveau suit",
    corps:"La posture ne fait pas que refléter ton état mental — elle l'influence. Se redresser augmente le sentiment de confiance et d'énergie, se tasser nourrit le doute. Avant un trade ou une décision, redresse-toi, épaules en arrière, respire. Ton corps envoie un signal de calme et de contrôle à ton cerveau.",
    source:"Cognition incarnée", auteur:"Psychologie" },
  { id:'p8', theme:'physique', titre:"Ta glycémie pilote ta lucidité",
    corps:"Des pics et chutes de sucre dans le sang déstabilisent ton humeur, ta concentration et ton self-control — mauvais pour décider. Des repas stables (protéines, fibres, bons gras), moins de sucres rapides, et ton cerveau garde un carburant régulier. On ne trade pas bien le ventre en montagnes russes.",
    source:"Nutrition & cognition", auteur:"Physiologie" },
  { id:'p9', theme:'physique', titre:"Marche pour débloquer tes idées",
    corps:"Marcher, surtout dehors, augmente nettement la créativité et aide à résoudre les problèmes sur lesquels tu bloques. Le mouvement doux met le cerveau dans un mode associatif où les idées se relient. Coincé sur une décision ? Ne force pas devant l'écran : lève-toi et marche 10 minutes. La solution vient souvent en chemin.",
    source:"Marche & créativité", auteur:"Étude Stanford" },

  { id:'a7', theme:'appren', titre:"Apprends, puis dors",
    corps:"Le meilleur moment pour dormir, c'est après avoir appris quelque chose d'important : le sommeil transfère l'info de la mémoire fragile vers la mémoire durable. Réviser une carte le soir, puis dormir, ancre bien mieux que réviser puis rester debout des heures. Fais du sommeil le dernier geste de ton apprentissage.",
    source:"Sommeil & mémoire", auteur:"Neurosciences du sommeil" },
  { id:'a8', theme:'appren', titre:"Enseigner, c'est apprendre deux fois",
    corps:"Quand tu expliques une idée à quelqu'un, tu es obligé de l'organiser, de la simplifier, de combler tes trous. C'est l'un des moyens les plus puissants d'ancrer un savoir. Prends l'habitude, après chaque carte, de la reformuler à voix haute comme si tu l'enseignais. Ce que tu peux transmettre, tu le possèdes vraiment.",
    source:"Effet protégé (learning by teaching)", auteur:"Sciences de l'apprentissage" },
  { id:'a9', theme:'appren', titre:"Regroupe pour mémoriser (chunking)",
    corps:"Ta mémoire de travail ne tient que ~4 éléments à la fois. L'astuce des experts : regrouper l'info en « paquets » qui font sens (un numéro de téléphone en blocs, un setup de trading en une seule image mentale). En reliant le nouveau à ce que tu sais déjà, tu transformes plein de détails en une seule idée solide.",
    source:"Chunking", auteur:"Sciences cognitives" },

  { id:'r7', theme:'reflex', titre:"L'explication la plus simple d'abord",
    corps:"Le rasoir d'Occam : face à plusieurs explications, la plus simple est souvent la bonne. En trading comme dans la vie, on invente des scénarios compliqués pour justifier ce qu'on veut croire. Reviens au plus simple : que disent les faits, sans histoire ? La complexité est souvent le déguisement d'un biais.",
    source:"Rasoir d'Occam", auteur:"Guillaume d'Ockham" },
  { id:'r8', theme:'reflex', titre:"Fais un pré-mortem",
    corps:"Avant une décision importante, imagine qu'on est dans six mois et que ça a échoué. Demande-toi : « qu'est-ce qui a mal tourné ? » Cet exercice révèle les risques que l'optimisme te cache. En trading : « si ce trade tourne mal, ce sera à cause de quoi ? » Tu prépares ta défense avant l'attaque.",
    source:"Pre-mortem", auteur:"Gary Klein" },
  { id:'r9', theme:'reflex', titre:"La carte n'est pas le territoire",
    corps:"Ton idée de la réalité n'est pas la réalité — c'est une carte, forcément simplifiée et parfois fausse. Le graphique n'est pas le marché ; ton plan n'est pas l'avenir. Reste humble face à tes modèles : garde-les tant qu'ils marchent, jette-les quand la réalité les contredit. Confondre la carte et le terrain, c'est foncer dans le mur avec confiance.",
    source:"Sémantique générale", auteur:"Alfred Korzybski" },
];

/* Niveaux de progression — de novice à monstre */
const NIVEAUX = [
  { seuil:0,    nom:"Étincelle",     emoji:"✨" },
  { seuil:50,   nom:"Apprenti",      emoji:"🌱" },
  { seuil:150,  nom:"Disciplié",     emoji:"🔥" },
  { seuil:350,  nom:"Combattant",    emoji:"⚔️" },
  { seuil:700,  nom:"Stratège",      emoji:"🧠" },
  { seuil:1200, nom:"Redoutable",    emoji:"⚡" },
  { seuil:2000, nom:"Monstre",       emoji:"👑" },
];

/* Citations d'accueil rotatives */
const CITATIONS = [
  "« Ton cerveau se reconstruit à chaque idée que tu graves. »",
  "« Un peu, mais tous les jours. C'est comme ça qu'on devient un monstre. »",
  "« Les neurones qui s'activent ensemble se lient ensemble. »",
  "« La discipline pèse des grammes, le regret pèse des tonnes. »",
  "« Le meilleur perdant gagne. »",
  "« 1 % par jour = 37 fois meilleur en un an. »",
];
